""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Vim config File by Thomas Scherf
"
"
"
"
"
"
"
" General {{{
set shell=/bin/bash

set backspace=2		" 
set nocompatible	" use vim settings instead of vi
set modeline        " allow comments at the end of files to set vim variables
set number			" show line numbers
set showcmd			" show command in the last line of the screen
set wildmenu        " command-line completion in enhanced mode
set wildchar=<Tab>  " key for completion
set showmatch       " jump to the matching word
set incsearch       " while tipping the search, show where the pattern matches
set hlsearch		" highligth search

set laststatus=2	" Always display the status line
filetype off        " required for vundle

let mapleader="."
syntax on
" }}}

" folding {{{
set foldenable          " when on, all fold are closed
set foldmethod=indent   " the kind of folding used
set foldlevel=99
" }}}

" use System clipboard
set clipboard=unnamed
" }}}

" Intendens, Tabbehavior {{{
set tabstop=2           " width of a tab character
set softtabstop=2       " tab will create (and backspace removes) that many spaces
set expandtab           " spaces not tabs 
set shiftwidth=2        " spaces for tab
set smarttab            "
" }}} 

" Mappings {{{
map <F2> :set paste<CR>i                " key to insert mode with paste using F2 key
map <leader>n :NERDTreeToggle<CR>       " open/close nerdtree
au InsertLeave * set nopaste            " Leave paste mode on exit
nnoremap <space> za
" }}}

"Color Scheme {{{
set background=dark " or light
colorscheme elflord
"colorscheme delek
"}}}

" ttyfast & lazydraw {{{
set ttyfast
set lazyredraw
" }}}

" Reduce timeout after <ESC> is recieved. {{{
set ttimeout
set ttimeoutlen=20
set notimeout
"}}}


" screen split {{{
set splitbelow
set splitright
" move between windows with ctrl+key
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

"}}}

" Backup {{{
set backup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set writebackup
"}}}

" Vumble {{{
set rtp+=~/.vim/bundle/Vundle.vim               " runtime path for vundle
call vundle#begin('~/.vim/bundle/Vundle.vim')


Plugin 'VundleVim/Vundle.vim'               " vundle requirment
" user plugins
"Plugin 'Valloric/YouCompleteMe'            " YouCompleteMe: code-completion
Plugin 'scrooloose/nerdtree'                " nerdtree: directory explorer
Plugin 'vim-airline/vim-airline'            " airline: statusbar
Plugin 'vim-airline/vim-airline-themes'     " airline-theme: themes for airline
Plugin 'edkolev/tmuxline.vim'               " tmuxline: tmux status line
Plugin 'ryanoasis/vim-devicons'             " icons for airline and nerdtree

call vundle#end()            " required
filetype plugin indent on    " required
"filetype plugin on
"}}}

" plugin setup {{{
"let g:ycm_python_binary_path = '/usr/bin/python3'

"autocmd vimenter * NERDTree

" airline
" https://github.com/vim-airline/vim-airline/wiki/Screenshots
let g:airline_theme='wombat'
let g:airline#extensions#tabline#enabled = 1

let g:airline_left_sep='>'
let g:airline_detect_paste=1

set noshowmode
set encoding=utf-8
set term=xterm-256color

" fonts {{{
set guifont=DroidSansMono\ Nerd\ Font\ 11
" }}}

" vim-devicons for airline
let g:airline_powerline_fonts = 1



" ycm teak
"let g:ycm_autoclose_preview_window_after_completion=1
"map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>
"}}}

" vim:foldmethod=marker:foldlevel=1

